version: 2
checks:
    argument-count:
        config:
            threshold: 7
exclude_patterns:
    - "doc/"
    - "examples/"
    - "tests/"
plugins:
    bandit:
        enabled: true
    Pep8:
        enabled: true
    Radon:
        enabled: true
    SonarPython:
        enabled: true
